/**
	Tourist application
	Библиотека сущностей
	Подключаемые файлы
*/
#ifndef TOURIST_OBJECTS_H
#define TOURIST_OBJECTS_H

#include "forward.h"
#include "ProjectRequest.h"
#include "ProjectOrder.h"
#include "ProjectTour.h"
#include "ProjectTRequest.h"
#include "ProjectTService.h"
#include "ProjectDirect.h"
#include "ProjectNameService.h"
#include "ProjectMUService.h"
#include "ProjectService.h"
#include "ProjectCountry.h"
#include "ProjectRRequest.h"
#include "ProjectSTour.h"
#include "ProjectGroup.h"
#include "ProjectTplTour.h"
#include "ProjectCity.h"
#include "ProjectClient.h"
#include "ProjectUser.h"
#include "ProjectSOrder.h"
#include "ProjectLog.h"
#include "ProjectClDoc.h"
#include "ProjectDocType.h"
#include "ProjectCurrency.h"
#include "ProjectCurrencyPair.h"
#include "ProjectCompany.h"
#include "ProjectPartner.h"
#include "ProjectPersAcc.h"
#include "ProjectPartnerReq.h"
#include "ProjectPartnerAnswr.h"
#include "ProjectRoute.h"
#include "ProjectAttach.h"
#include "ProjectPriceTableItem.h"
#include "ProjectSRequest.h"
#include "ProjectClientUr.h"
#include "ProjectReport.h"
#include "ProjectObjectLink.h"
#include "ProjectObjectLock.h"
#include "ProjectFinance.h"
#include "ProjectDocTemplate.h"
#include "ProjectDocTemplatePrinted.h"
#include "ProjectTourPayOrder.h"
#include "ProjectTourApps.h"
#include "ProjectTransferPoint.h"
#include "ProjectRoute.h"
#include "ProjectHostSide.h"
#include "ProjectTouristList.h"

#endif
