
#ifndef INCLUDE_DATAMODEL_H
#define INCLUDE_DATAMODEL_H

#include "ProjectRequest.h"
#include "ProjectOrder.h"
#include "ProjectTour.h"
#include "ProjectTRequest.h"
#include "ProjectTService.h"
#include "ProjectDirect.h"
#include "ProjectNameService.h"
#include "ProjectMUService.h"
#include "ProjectService.h"
#include "ProjectCountry.h"
#include "ProjectRRequest.h"
#include "ProjectSTour.h"
#include "ProjectGroup.h"
#include "ProjectTplTour.h"
#include "ProjectCity.h"
#include "ProjectClient.h"
#include "ProjectUser.h"
#include "ProjectSOrder.h"
#include "ProjectLog.h"
#include "ProjectClDoc.h"
#include "ProjectDocType.h"
#include "ProjectCurrency.h"
#include "ProjectCurrencyPair.h"
#include "ProjectCompany.h"
#include "ProjectPartner.h"
#include "ProjectPersAcc.h"
#include "ProjectPartnerReq.h"
#include "ProjectPartnerAnswr.h"
#include "ProjectRoute.h"
#include "ProjectAttach.h"
#include "ProjectPriceTableItem.h"
#include "ProjectSRequest.h"
#include "ProjectClientUr.h"
#include "ProjectReport.h"
#include "ProjectObjectLock.h"
#include "ProjectDocTemplate.h"
#include "ProjectDocTemplatePrinted.h"
#include "ProjectTourPayOrder.h"
#include "ProjectTransferPoint.h"
#include "ProjectHostSide.h"
#include "ProjectTouristList.h"
#include "ProjectGroupPeriod.h"
#include "ProjectReportLanding.h"
#include "ProjectReportFilling.h"
#include "ProjectReportGroupPay.h"
#include "ProjectReportHotelPay.h"
#include "ProjectReportDayPay.h"

#include "project.h"
#include "infohandler.h"

#endif
